name: "🐞 Bug Report"
description: "Report a problem or unexpected behavior."
title: "[Bug] "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping improve Textual Theme Generator!
  - type: input
    id: summary
    attributes:
      label: "Short summary"
      description: "Briefly describe the bug."
      placeholder: "e.g. Theme preview does not update after editing colors."
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: "Steps to reproduce"
      description: "How can we reproduce the bug?"
      placeholder: "1. Go to ...\n2. Click ...\n3. See error ..."
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: "Expected behavior"
      description: "What did you expect to happen?"
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: "Actual behavior"
      description: "What actually happened?"
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: "Browser/Device"
      description: "(Optional) What browser/device are you using?"
      placeholder: "e.g. Chrome 124, Windows 11, iPhone 15"
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots or recordings"
      description: "(Optional) Add screenshots or a screen recording if possible."
    validations:
      required: false
  - type: textarea
    id: extra
    attributes:
      label: "Additional context"
      description: "(Optional) Anything else we should know?"
    validations:
      required: false
