name: "💬 Feedback or Question"
description: "Share your thoughts, ask a question, or give general feedback."
title: "[Feedback] "
labels: [feedback]
body:
  - type: markdown
    attributes:
      value: |
        We welcome feedback from everyone! You don't need to be a developer—just let us know what you think or ask any question.
  - type: textarea
    id: feedback
    attributes:
      label: "Your feedback or question"
      description: "What would you like to share or ask?"
      placeholder: "e.g. I love the theme editor, but I wish it had more color options!"
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: "Browser/Device (optional)"
      description: "If relevant, what browser/device are you using?"
      placeholder: "e.g. Firefox, Android phone, iPad"
    validations:
      required: false
  - type: textarea
    id: extra
    attributes:
      label: "Anything else? (optional)"
      description: "Any other comments or context?"
    validations:
      required: false
