/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const IconCharmCross: typeof import('~icons/charm/cross.jsx')['default']
  const IconDeviconPython: typeof import('~icons/devicon/python.jsx')['default']
  const IconMaterialSymbolsCheckRounded: typeof import('~icons/material-symbols/check-rounded.jsx')['default']
  const IconMdiAlert: typeof import('~icons/mdi/alert.jsx')['default']
  const IconMdiCheck: typeof import('~icons/mdi/check.jsx')['default']
  const IconMdiChevronUpDown: typeof import('~icons/mdi/chevron-up-down.jsx')['default']
  const IconMdiClose: typeof import('~icons/mdi/close.jsx')['default']
  const IconMdiCog: typeof import('~icons/mdi/cog.jsx')['default']
  const IconMdiContentCopy: typeof import('~icons/mdi/content-copy.jsx')['default']
  const IconMdiDice: typeof import('~icons/mdi/dice.jsx')['default']
  const IconMdiDotsHorizontal: typeof import('~icons/mdi/dots-horizontal.jsx')['default']
  const IconMdiEyeOffOutline: typeof import('~icons/mdi/eye-off-outline.jsx')['default']
  const IconMdiEyeOutline: typeof import('~icons/mdi/eye-outline.jsx')['default']
  const IconMdiFileExportOutline: typeof import('~icons/mdi/file-export-outline.jsx')['default']
  const IconMdiFileImportOutline: typeof import('~icons/mdi/file-import-outline.jsx')['default']
  const IconMdiGithub: typeof import('~icons/mdi/github.jsx')['default']
  const IconMdiMixerSettings: typeof import('~icons/mdi/mixer-settings.jsx')['default']
  const IconMdiPalette: typeof import('~icons/mdi/palette.jsx')['default']
  const IconMdiPencilCircle: typeof import('~icons/mdi/pencil-circle.jsx')['default']
  const IconMdiPencilCircleOutline: typeof import('~icons/mdi/pencil-circle-outline.jsx')['default']
  const IconMdiPencilOutline: typeof import('~icons/mdi/pencil-outline.jsx')['default']
  const IconMdiPlus: typeof import('~icons/mdi/plus.jsx')['default']
  const IconMdiPlusCircle: typeof import('~icons/mdi/plus-circle.jsx')['default']
  const IconMdiThemeLightDark: typeof import('~icons/mdi/theme-light-dark.jsx')['default']
  const IconMdiTrashCanOutline: typeof import('~icons/mdi/trash-can-outline.jsx')['default']
  const IconPixelarticonsSectionCopy: typeof import('~icons/pixelarticons/section-copy.jsx')['default']
  const IconSvgSpinnersBlocksWave: typeof import('~icons/svg-spinners/blocks-wave.jsx')['default']
  const IconTablerMoonFilled: typeof import('~icons/tabler/moon-filled.jsx')['default']
  const IconTablerSunFilled: typeof import('~icons/tabler/sun-filled.jsx')['default']
}
