name: CI Checks

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Lint and format
        run: |
          bun check
          bun format:check

      - name: Type check
        run: bun ts-lint

      - name: Run tests
        run: bun test

      - name: Build project
        run: bun run build

      - name: Upload coverage report
        if: success() && always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/
